server:
  port: 8080

client:
  max-idle-conns: 500
  max-idle-conns-per-host: 100
  idle-conn-timeout: 10m
  timeout: 2m
  retry-count: 5
  retry-wait-time: 2s
  retry-max-wait-time: 10s

interrupter:
  initial-delay: 30m